name: controlador_bomba_de_insulina
description: Aplicação para controlar uma bomba de insulina
publish_to: 'none'

version: 0.0.1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  intl: ^0.18.1
  flutter_blue_plus: ^1.28.14
  permission_handler: ^10.4.3
  sqflite: ^2.3.0
  path: ^1.8.3
  image_picker: ^1.0.4
  syncfusion_flutter_charts: ^23.1.44
  csv: ^5.1.1
  path_provider: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
